# Generated by Django 2.2.4 on 2019-08-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('geo_ip_isp', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_ip_city', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_ip_country_code', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_ip_country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_ip_latitude', models.FloatField(blank=True, null=True)),
                ('geo_ip_longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
