# Generated by Django 2.2.4 on 2019-08-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PythonChallengeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddresses',
            name='geo_ip_isp',
        ),
        migrations.AlterField(
            model_name='ipaddresses',
            name='geo_ip_latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipaddresses',
            name='geo_ip_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
